project_name: aga
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
    goos:
      - linux
    goarch:
      - amd64
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.sha256"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
    homepage:  https://github.com/agaUHO/aga
    description: Modulo  AGA
    maintainer: TEAM AGA <aga@uho.edu.cu>
    license: MIT
    vendor: Akosej
    formats:
      - deb